repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ "--fix" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [ "--install-types", "--non-interactive" ]

  - repo: local
    hooks:
      - id: pytest
        name: run pytest
        entry: poetry run pytest -v
        language: system
        types: [ python ]
