repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ "--fix" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [ "--install-types", "--non-interactive" ]

  - repo: local
    hooks:
      - id: build-tree-sitter
        name: build tree-sitter java grammar
        entry: bash -c 'export TREE_SITTER_JAVA_PATH=$HOME/tree-sitter-java && poetry run python scripts/build_grammar.py'
        language: system
        pass_filenames: false

      - id: pytest
        name: run pytest
        entry: bash -c 'export TREE_SITTER_JAVA_PATH=$HOME/tree-sitter-java && poetry run pytest'
        language: system
        types: [ python ]
