[tool.poetry]
name = "project-insight-crawler"
version = "0.1.0"
description = "Crawler module for Project Insight"
authors = ["Gustavo A. Gutkoski <gustavogutkoski2609@gmail.com>"]
readme = "README.md"
packages = [{ include = "crawler" }]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
